#!/bin/bash

HOST_PORT=${1:-3000}

if [[ ! -z "$(docker images -q landing_pages/client_web:latest)" ]]; then
  docker run -dp $HOST_PORT:3000 landing_pages/client_web:latest
else
  echo 'There is no latest image for landing_pages/client_web'
fi
